### ISSUE TITLE
Create a new branch

### ISSUE THREAD

**Issue by ps-19** [Mboalab/Mboalab_Outreachy-May-Aug-2022#76]
The issue is a request to add a feature of new branch to ensure the data integrity of all participant at current stage of code-base.

Steps -

![image](https://user-images.githubusercontent.com/63330165/163916624-1ee353a0-ec17-48a2-990a-d5e7569b907f.png)
![image](https://user-images.githubusercontent.com/63330165/163916645-eaaef1ed-8a42-4dfd-aa07-669ae7c70024.png)
![image](https://user-images.githubusercontent.com/63330165/163916670-ab0313bd-ebae-42ec-b599-852a7a756677.png)
![image](https://user-images.githubusercontent.com/63330165/163916688-8493826d-9ff2-4b88-a532-fb7e20d9d725.png)

@jafsia sir please look into this matter as only you have access to create a new branch in this repository.
Thank You.

**Comment by PetraAG** [comment]
cool
